#برای بالا آوردن همزمان FastAPI و Nginx:
version: "3.9"          #مشخص می‌کنه که از نسخه ۳.۹ از syntax داکر کامپوز استفاده می‌کنیم. این یکی از نسخه‌های پایدار و رایج هست.

services:               #این قسمت تعریف همه ی سرویس‌هایی هست که در این پروژه اجرا می‌شن.
  fastapi-app:          #سرویس اول:

    build: .            # می‌گه داکر باید از دایرکتوری فعلی ( جایی که Dockerfile هست)  ایمیج بسازه.
                        #یعنی Dockerfile توی همون فولدریه که docker-compose.yml هست.

    container_name: fastapi-app        #اسم کانتینری که ساخته میشه، میشه fastapi. این اسم توی docker ps نشون داده میشه.
    ports:
      - "8000:8000"      #فقط برای استفاده داخلی بین کانتینرهاست (نه برای دسترسی بیرونی).
      # می‌گه پورت ۸۰۰۰ رو برای سرویس‌های دیگه (مثل nginx) قابل دسترسی کن.
    restart: always

    networks:           #این سرویس عضو شبکه‌ای به نام app-network میشه و کانتینرهای داخل یک شبکه می‌تونن با هم ارتباط داشته باشن
      - app-network


  nginx:                #سرویس دوم :
    image: nginx:latest  #می‌گه از آخرین نسخه Nginx موجود در Docker Hub استفاده کن.
    container_name: nginx  #اسم کانتینری که اجرا میشه: nginx
    ports:              #پورت ۸۰ روی سیستم ما (host) رو به پورت ۸۰ داخل container وصل می‌کنه.
      - "80:80"          #پس وقتی مرورگر رو باز میکنیم و به http://localhost میریم درخواست ها به Nginx می‌رسه.

    volumes:               #پیکربندی اختصاصی Nginx پروژه ما رو وارد کانتینر می‌کنه. یعنی داری به Nginx می‌گی «این فایل تنظیمات من رو استفاده کن».
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static
    depends_on:
      - fastapi-app        #می‌گه این سرویس (nginx) بعد از راه‌اندازی fastapi اجرا بشه.
                          # اما depends_on فقط ترتیب رو تنظیم می‌کنه، نه اینکه منتظر سالم بودن FastAPI بمونه.
    restart: always
    networks:              #اینجا هم Nginx در همون شبکه‌ای هست که  FastAPI هم  هست، پس می‌تونه با اسم fastapi بهش وصل بشه
      - app-network


networks:                #تعریف شبکه:
  app-network:
    driver: bridge

#یک شبکه مشترک بین Nginx و FastAPI برای ارتباط داخلی
#یک شبکه مجازی به اسم app-network تعریف شده با bridge به عنوان درایور.
#تمام کانتینرهایی که عضو این شبکه هستن می‌تونن همدیگه رو با اسم سرویس‌ها شناسایی کنن.
#مثلاً داخل Nginx می‌تونی http://fastapi:8000 بنویسی.